import = ["~/.config/alacritty/themes/snazzy.toml"]

[shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
opacity = 0.8

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 14.0

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 750
blink_timeout = 5
thickness = 0.15

[mouse]
hide_when_typing = true
